# Generated by Django 6.0.6 on 2026-07-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
            ],
        ),
    ]
